- name: Install podman
  apt:
    package:
      - podman

- name: Install Python development tools
  apt:
    package:
      - black
      - mypy
      - flake8
      - python3-numpy
      - python3-matplotlib
      - python3-all-dbg
      - python3-all-dev
  tags: python

- name: Install essential development tools
  apt:
    package:
      - autopkgtest
      - build-essential
      - ccache
      - debhelper
      - equivs
      - git
      - git-buildpackage
      - mmdebstrap
      - shellcheck
      - sqlite3
      - ubuntu-dev-tools
      - valgrind

- name: APT pre-build and test dependencies
  apt:
    package:
      - clang-format
      - db-util
      - stunnel4
      - valgrind
      - python3-feedparser

- name: git-ubuntu
  snap:
    name:
      - git-ubuntu
    classic: true

- name: lp-to-jira
  snap:
    name:
      - lp-to-jira

- name: Bootstrap ansible
  apt:
    package:
      - ansible-core
      - ansible-lint

- name: Bootstrap qemu
  apt:
    package:
      - qemu-system
      - qemu-user-static
      - qemu-efi-aarch64
      - ovmf


- name: Android
  apt:
    package:
      - adb
      - scrcpy
