- name: Install podman
  apt:
    package:
      - podman

- name: Install Python development tools
  apt:
    package:
      - black
      - mypy
      - flake8
      - python3-numpy
      - python3-matplotlib
      - python3-all-dbg
      - python3-all-dev
  tags: python

- name: Install essential development tools
  apt:
    package:
      - autopkgtest
      - build-essential
      - ccache
      - debhelper
      - git
      - git-buildpackage
      - mmdebstrap
      - sqlite3
      - ubuntu-dev-tools
      - valgrind

- name: git-ubuntu
  snap:
    name:
      - git-ubuntu
    classic: true

- name: lp-to-jira
  snap:
    name:
      - lp-to-jira

- name: Bootstrap ansible
  apt:
    package:
      - ansible-core
      - ansible-lint
      - ansible-mitogen

- name: Bootstrap qemu
  apt:
    package:
      - qemu-system
      - qemu-user-static
      - qemu-efi-aarch64
      - ovmf
