- name: Install podman
  apt:
    package:
      - podman

- name: Install essential development tools
  apt:
    package:
      - build-essential
      - git
      - mmdebstrap
      - sqlite3

- name: Bootstrap ansible
  apt:
    package:
      - ansible-core
      - ansible-lint
      - ansible-mitogen
