- name: Install podman
  apt:
    package:
      - podman

- name: Install essential development tools
  apt:
    package:
      - autopkgtest
      - build-essential
      - git
      - mmdebstrap
      - sqlite3
      - ubuntu-dev-tools

- name: Bootstrap ansible
  apt:
    package:
      - ansible-core
      - ansible-lint
      - ansible-mitogen

- name: Bootstrap qemu
  apt:
    package:
      - qemu-system
      - qemu-user-static
      - qemu-efi-aarch64
      - ovmf
