- name: Install dotfiles
  shell:
    cmd: git clone https://github.com/julian-klode/dotfiles.git dotfiles &&  GIT_DIR=dotfiles/.git  git stash && GIT_DIR=dotfiles/.git git checkout && mv dotfiles/.git .hgit && rm -r dotfiles
    chdir: /home/jak
    creates: /home/jak/.hgit

- name: Enable systemd-tmpfiles-setup.service
  systemd:
    scope: user
    service: systemd-tmpfiles-setup.service
    enabled: true
    state: started

- name: Enable systemd-tmpfiles-clean.timer
  systemd:
    scope: user
    service: systemd-tmpfiles-clean.timer
    enabled: true
    state: started

- name: Enable borg@rsyncnet.timer
  systemd:
    scope: user
    service: borg@rsyncnet.timer
    enabled: true
    state: started

- name: Add flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  tags: flatpak

- name: Install portfolio-performance
  flatpak:
    name: info.portfolio_performance.PortfolioPerformance
    state: present
    method: user
  tags: flatpak

- name: Configure right windows key to act as second alt gr, capslock to act as windows key
  dconf:
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['caps:super', 'lv3:rwin_switch', 'lv3:ralt_switch']"

- name: Configure keyboard layouts
  dconf:
    key: /org/gnome/desktop/input-sources/sources
    value: "[('xkb', 'de+nodeadkeys'), ('xkb', 'de'), ('xkb', 'us')]"

- name: Move syncthing config
  command:
    cmd: mv /home/jak/snap/syncthing/common/syncthing /home/jak/.config/
    removes: /home/jak/snap/syncthing/common/syncthing
    creates: /home/jak/.config/syncthing
  tags: internet

- name: Move syncthing data
  command:
    cmd: sh -c "test -d /home/jak/Sync || rm /home/jak/Sync && mv /home/jak/snap/syncthing/common/Sync /home/jak/"
    removes: /home/jak/snap/syncthing/common/Sync
  tags: internet

- name: Adjust syncthing config
  ansible.builtin.replace:
    path: /home/jak/.config/syncthing/config.xml
    regexp: /home/jak/snap/syncthing/common/Sync
    replace: /home/jak/Sync
  tags: internet

- name: Start syncthing
  systemd:
    name: syncthing.service
    enabled: yes
    state: started
    scope: user
  tags: internet
