- name: Install dotfiles
  shell:
    cmd: git clone https://github.com/julian-klode/dotfiles.git dotfiles &&  GIT_DIR=dotfiles/.git  git stash && GIT_DIR=dotfiles/.git git checkout && mv dotfiles/.git .hgit && rm -r dotfiles
    chdir: /home/jak
    creates: /home/jak/.hgit

- name: Enable systemd-tmpfiles-setup.service
  systemd:
    scope: user
    service: systemd-tmpfiles-setup.service
    enabled: true
    state: started

- name: Enable systemd-tmpfiles-clean.timer
  systemd:
    scope: user
    service: systemd-tmpfiles-clean.timer
    enabled: true
    state: started

- name: Enable borg@rsyncnet.timer
  systemd:
    scope: user
    service: borg@rsyncnet.timer
    enabled: true
    state: started

- name: Add flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  tags: flatpak

- name: Install portfolio-performance
  flatpak:
    name: info.portfolio_performance.PortfolioPerformance
    state: present
    method: user
  tags: flatpak

- name: Configure right windows key to act as second alt gr, capslock to act as windows key
  dconf:
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['caps:super', 'lv3:rwin_switch', 'lv3:ralt_switch']"

- name: Configure keyboard layouts
  dconf:
    key: /org/gnome/desktop/input-sources/sources
    value: "[('xkb', 'de+nodeadkeys'), ('xkb', 'de'), ('xkb', 'us')]"
