- name: Install tlp
  apt:
     package: tlp

- name: Install libmbim-utils
  apt:
     package: libmbim-utils
  when: "'wwan0' in ansible_facts and ansible_facts.wwan0.module == 'cdc_mbim'"
  tags: internet

- name: Configure SuspendState
  copy:
     dest: /etc/systemd/sleep.conf.d
     content: |
      [Sleep]
      SuspendState=freeze
     mode: 0644
  when: "ansible_facts.product_version == 'ThinkPad T14 Gen 3'"
  notify:
     - systemctl daemon-reload
