- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install keybase
  apt:
    deb: https://prerelease.keybase.io/keybase_amd64.deb
  when: "'keybase' not in ansible_facts.packages"


